aliases: []
creation_timestamp: 1739784098761
current_stage: None
description: null
last_updated_timestamp: 1739784098761
name: Support Vector Classifier
run_id: 3e2e74fa09514b62b680c74a1a0c1706
run_link: null
source: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/274130883395714487/3e2e74fa09514b62b680c74a1a0c1706/artifacts/Support
  Vector Classifier
status: READY
status_message: null
storage_location: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/274130883395714487/3e2e74fa09514b62b680c74a1a0c1706/artifacts/Support
  Vector Classifier
user_id: null
version: 1
