aliases: []
creation_timestamp: 1739783923556
current_stage: None
description: null
last_updated_timestamp: 1739783923556
name: Gradient Boosting Classifier
run_id: 00d9a08f488e416488d86abff950afbe
run_link: null
source: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/274130883395714487/00d9a08f488e416488d86abff950afbe/artifacts/Gradient
  Boosting Classifier
status: READY
status_message: null
storage_location: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/274130883395714487/00d9a08f488e416488d86abff950afbe/artifacts/Gradient
  Boosting Classifier
user_id: null
version: 1
