aliases: []
creation_timestamp: 1739781527959
current_stage: None
description: null
last_updated_timestamp: 1739781527959
name: Logistic Regression
run_id: e8e2d81a200d4758ab980e6a39598f42
run_link: null
source: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/798228184358758638/e8e2d81a200d4758ab980e6a39598f42/artifacts/Logistic
  Regression
status: READY
status_message: null
storage_location: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/798228184358758638/e8e2d81a200d4758ab980e6a39598f42/artifacts/Logistic
  Regression
user_id: null
version: 1
