aliases: []
creation_timestamp: 1739781468509
current_stage: None
description: null
last_updated_timestamp: 1739781468509
name: Naive Bayes Classifier
run_id: 59de8de412c048cf900bde711011f8cb
run_link: null
source: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/798228184358758638/59de8de412c048cf900bde711011f8cb/artifacts/Naive
  Bayes Classifier
status: READY
status_message: null
storage_location: file:///d:/CMI/CMI_Git/AppliedML/Assignment 2/mlflow/798228184358758638/59de8de412c048cf900bde711011f8cb/artifacts/Naive
  Bayes Classifier
user_id: null
version: 1
